### PR TITLE
Feature/add tags to form inputs

### LINKED ISSUE #220: Add html tags to allow easier fulfilment of text fields
HTML defines the `autocomplete` attribute (see [The autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)) which can be used by browsers to suggest inputs to the users.

In addition to adding this attributes it could be useful to disable spellchecks on the document number field.

---

Thank you for the effort you put in this project; I hope you accept contributions and will make a PR in the next couple minutes.

### PR DESCRIPTION
**Pull request by tom139**
fixes #220 by adding `autocomplete` and `spellcheck` tags in forms.

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @tom139 ! Thanks for your contributions! Could you please start from and also target to the develop branch? Let me know if you need help in this sense 😄

**Comment by tom139** [comment]
Ehi @DavidePastore, yep, no problem. I thought main and develop were identical but it is not the case. I will close this PR and open a new one, referencing the same issue.

**Comment by tom139** [comment]
@DavidePastore I've seen there is some issue with the html validation action.
I'm checking the code I pushed and will comment again as soon if I have an update.

**Comment by DavidePastore** [comment]
Yes @tom139 . It seems the validator is not expecting some additional HTML attributes. In the meantime I'm working on enabling the html_check workflow even on PR, so we can easily get the output of it before merging.

**Comment by tom139** [comment]
Great for PR validation 👍🏽.
I've found that `autocorrect` is listed among [non standard attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#non-standard_attributes) as a Safari-only extension in the Mozilla documentation.

**Comment by DavidePastore** [comment]
The validation should be enabled on PRs too. 

> I've found that autocorrect is listed among non standard attributes as a Safari-only extension in the Mozilla documentation.

In this case we could remove it.

**Comment by DavidePastore** [comment]
@tom139 , it seems that `autocomplete="street-address"` is related to the `textarea` tag and cannot be used for `input type="text"`. [Check it here](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-street-address).

**Comment by tom139** [comment]
What do you suggest for `street-address`? I will change it to `address-line-1`, let me know if you think it is better to change the input to a `textarea`.

Regarding the Safari only `autocomplete` tag I will remove it.

**Comment by DavidePastore** [comment]
Thanks @tom139 . I think that for the moment it's ok to use `address-line-1`.

**Pull request closed without merging**
